# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the tag on this image to a more stable version, using latest can result in unstable builds.
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          working_directory: .
          name: Install paket & dotcover
          command: |
            dotnet tool restore
      - run:
          working_directory: .
          name: Restore packages
          command: |
            dotnet paket restore
      - run:
          working_directory: tests/Roslyn.Architecture.Tests
          name: Build tests
          command: |
            dotnet build -c Debug
      - run:
          working_directory: tests/Roslyn.Architecture.Tests
          name: Run tests with code coverage
          command: |
            dotnet coverlet bin/Debug/net6.0/Roslyn.Architecture.Tests.dll -f opencover --target "dotnet" --targetargs "test --no-build" 
      - run:
          working_directory: tests/Roslyn.Architecture.Tests
          name: Run report generator
          command: |
            dotnet reportgenerator -reports:coverage.opencover.xml -targetdir:coverage
      - run:
          working_directory: tests/Roslyn.Architecture.Tests
          name: Upload coverage to codecov
          command: |
            curl -Os https://uploader.codecov.io/v0.1.17/linux/codecov
            chmod +x codecov
            ./codecov -f coverage.opencover.xml
      - run:
          working_directory: src/Roslyn.Architecture.Package
          name: Pack roslyn analyzer package
          command: |
            dotnet build -c release
      - run:
          working_directory: src/Roslyn.Architecture.Abstractions
          name: Pack attributes package
          command: |
            dotnet build -c release
      - store_artifacts:
          path: src/nupkg
          destination: nuget_package
      - store_artifacts:
          path: tests/Roslyn.Architecture.Package/coverage
          destination: coverage
      - persist_to_workspace:
          root: src
          paths:
            - nupkg

  publish-to-nuget:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - attach_workspace:
          at: .
      - run:
          dotnet nuget push --source "${NUGET_FEED_URL}" --api-key="${NUGET_KEY}" nupkg/*.nupkg


workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  build-and-publish:
    jobs:
      - build-and-test
      - publish-to-nuget:
          filters:
            branches:
              only: master
          requires:
            - build-and-test
          context: "Main context"
