name: publish-packages
on: 
  push:
    branches:
      - master
jobs:
  build-and-test-analyzer:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install paket & dotcover
        run: dotnet tool restore
        working_directory: .
