name: publish-packages
on: 
  push:
    branches:
      - master
jobs:
  build-and-test-analyzer:
    container: mcr.microsoft.com/dotnet/sdk:6.0
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install paket & coverlet
        run: dotnet tool restore
        working-directory: .
      - name: Restore packages
        working-directory: .
        run: dotnet paket restore
      - name: Build tests
        working-directory: tests/Roslyn.Architecture.Tests/
        run: dotnet build -c Debug
